import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { FormEvent, useState } from "react";
export interface IShopCard {
  id: string;
  price: string;
  title: string;
  gender: string;
  img: string;
  description: string;
}
interface Props {
  dataShopFilter: IShopCard[];
}

const Shop: NextPage<Props> = ({ dataShopFilter }) => {
  const router = useRouter();
  const [shopInputVal, setShopInputVal] = useState("");

  const shopInputHandler = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (shopInputVal.trim().length === 0) {
      const { q, ...restQuery } = router.query;
      router.push({
        query: restQuery,
      });
    } else {
      router.push({
        query: { ...router.query, q: shopInputVal },
      });
    }
  };

  const filterHandler = (e: any) => {
    const clickedFilter = e.target.value;

    if (clickedFilter === "man" || clickedFilter === "women") {
      return router.push({
        query: { ...router.query, gender: clickedFilter },
      });
    } else {
      if (clickedFilter !== "*") {
        router.push({
          query: {
            ...router.query,
            q: clickedFilter,
          },
        });
      } else {
        router.push({
          query: {},
        });
        setShopInputVal("");
      }
    }
  };
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg0 m-t-23 p-b-140">
        <div className="container">
          <div className="flex-w flex-sb-m p-b-52">
            <div className="flex-w flex-l-m filter-tope-group m-tb-10">
              <button
                value={"*"}
                onClick={filterHandler}
                className={`stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 
                ${Object.keys(router.query).length === 0 ? "how-active1" : ""}`}
              >
                All Products
              </button>

              <button
                onClick={filterHandler}
                value={"women"}
                className={`stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 ${
                  router.query.gender?.includes("women") ? "how-active1" : ""
                }`}
              >
                Women
              </button>

              <button
                onClick={filterHandler}
                value={"man"}
                className={`stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 ${
                  router.query.gender?.includes("man") ? "how-active1" : ""
                }`}
              >
                Men
              </button>

              <button
                onClick={filterHandler}
                value={"belt"}
                className={`stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 ${
                  router.query.q?.includes("belt") ? "how-active1" : ""
                }`}
              >
                Belt
              </button>

              <button
                onClick={filterHandler}
                value={"shoes"}
                className={`stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 ${
                  router.query.q?.includes("shoes") ? "how-active1" : ""
                }`}
              >
                Shoes
              </button>

              <button
                onClick={filterHandler}
                value={"watches"}
                className={`stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 ${
                  router.query.q?.includes("watches") ? "how-active1" : ""
                }`}
              >
                Watches
              </button>
            </div>

            <div className="flex-w flex-c-m m-tb-10">
              <div className="flex-c-m stext-106 cl6 size-105 bor4 pointer hov-btn3 trans-04 m-tb-4 js-show-search show-search">
                <i className="icon-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-search"></i>
                Search
              </div>
            </div>

            {/* search */}
            <div className="panel-search w-full p-t-10 p-b-15">
              <form
                onSubmit={shopInputHandler}
                className="bor8 dis-flex p-l-15"
              >
                <button
                  type="submit"
                  className="size-113 flex-c-m fs-16 cl2 hov-cl1 trans-04"
                >
                  <i className="zmdi zmdi-search"></i>
                </button>

                <input
                  value={shopInputVal}
                  onChange={(e) => setShopInputVal(e.target.value)}
                  className="mtext-107 cl2 size-114 plh2 p-r-15"
                  type="text"
                  name="search-product"
                  placeholder="Search"
                />
              </form>
            </div>
          </div>

          <div className="row isotope-grid">
            {dataShopFilter.length == 0 && <h1>There are no results</h1>}
            {dataShopFilter.map((card) => {
              return (
                <div
                  key={card.id}
                  className="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item women"
                >
                  <div className="block2">
                    <div className="block2-pic hov-img0">
                      <img src={card.img} alt={`${card.title}-picutre`} />
                      <Link href={`shop/${card.id}`}>
                        <a className="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1">
                          View Details
                        </a>
                      </Link>
                    </div>

                    <div className="block2-txt flex-w flex-t p-t-14">
                      <div className="block2-txt-child1 flex-col-l ">
                        <a
                          href="product-detail.html"
                          className="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6"
                        >
                          {card.title}
                        </a>

                        <span className="stext-105 cl3">{card.price}</span>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          <div className="flex-l-m flex-w w-full p-t-10 m-lr--7">
            <a
              href="#"
              className="flex-c-m how-pagination1 trans-04 m-all-7 active-pagination1"
            >
              1
            </a>

            <a href="#" className="flex-c-m how-pagination1 trans-04 m-all-7">
              2
            </a>

            <a href="#" className="flex-c-m how-pagination1 trans-04 m-all-7">
              3
            </a>
          </div>
        </div>
      </div>
    </>
  );
};

export default Shop;
export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const q = query.q;
  const gender = query.gender;
  let link = "";
  if (q && gender) {
    link = `http://localhost:5001/products?gender_like=${gender}&q=${q}`;
  } else if (gender) {
    link = `http://localhost:5001/products?gender_like=${gender}`;
  } else if (q) {
    link = `http://localhost:5001/products?q=${q}`;
  } else {
    link = `http://localhost:5001/products`;
  }

  const resShopFilter = await fetch(link);
  const dataShopFilter = await resShopFilter.json();
  return {
    props: { dataShopFilter },
  };
};
