import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner, { IHomeBannerTitle } from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs, { IHomeBlog } from "../components/FeaturedBlogs";
import FeaturedProducts, {
  IHomeFeatured,
} from "../components/FeaturedProducts";

interface Props {
  dataHomeBanner: IHomeBannerTitle;
  dataHomeFeatured: IHomeFeatured[];
  dataHomeBlock: IHomeBlog[];
}
const Home: NextPage<Props> = ({
  dataHomeBanner,
  dataHomeFeatured,
  dataHomeBlock,
}) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner {...dataHomeBanner} />
      {/* after, we need the shop page  */}
      <CategoryPicker />

      <FeaturedProducts data={dataHomeFeatured} />

      <FeaturedBlogs data={dataHomeBlock} />
    </>
  );
};

export default Home;
export const getStaticProps: GetStaticProps = async () => {
  const resHomeBanner = await fetch("http://localhost:5001/banner_content");
  const dataHomeBanner = await resHomeBanner.json();

  const resHomeFeatured = await fetch(
    "http://localhost:5001/products/?_limit=4"
  );
  const dataHomeFeatured = await resHomeFeatured.json();

  const resHomeBlock = await fetch("http://localhost:5001/blogs/?_limit=3");
  const dataHomeBlock = await resHomeBlock.json();
  return {
    props: { dataHomeBanner, dataHomeFeatured, dataHomeBlock },
  };
};
