import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import BlogItem from "../components/BlogItem";
import PageTitle from "../components/PageTitle";
import ProductItem from "../components/ProductItem";
import { IBlogData } from "./blog";
import { IHomeFeatured } from "../components/FeaturedProducts";
interface Props {
  dataSearchBlog: IBlogData[];
  dataSearchItems: IHomeFeatured[];
}
const Search: NextPage<Props> = ({ dataSearchBlog, dataSearchItems }) => {
  return (
    <>
      <Head>
        <title>Store - Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={"Search"} />

      <div className="bg0 m-t-23 p-b-140 mt-5">
        <div className="container">
          <>
            <h2 className="mb-5">Blogs</h2>
            <div className="row isotope-grid">
              <div className="col-4">
                {dataSearchBlog.length === 0 && (
                  <h1 className="mb-5 text-danger">No Blogs Founded</h1>
                )}
                {dataSearchBlog.map((blog) => (
                  <BlogItem key={blog.id} {...blog} />
                ))}
              </div>
            </div>
          </>

          <div>
            <h2 className="mb-5">Products</h2>
            <div className="row isotope-grid">
              <div className="col-4">
                {dataSearchItems.length === 0 && (
                  <h1 className="mb-5 text-danger">No Products Founded</h1>
                )}
                {dataSearchItems.map((item) => (
                  <ProductItem key={item.id} {...item} />
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Search;
export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  if (query.q) {
    const resSearchBlog = await fetch(
      `http://localhost:5001/blogs?q=${query.q}`
    );
    const dataSearchBlog = await resSearchBlog.json();
    const resSearchItems = await fetch(
      `http://localhost:5001/products?q=${query.q}`
    );
    const dataSearchItems = await resSearchItems.json();
    return {
      props: { dataSearchBlog, dataSearchItems },
    };
  }
  return {
    props: {},
  };
};
